### ISSUE TITLE
Arrow OS bug

### ISSUE THREAD

**Issue by TatshSiow** [Coxxs/hide-tablet-taskbar#1]
Device : Mi Pad 5 Pro
OS : Arrow OS 13.1
Issues : After flashing this, the pill disappears, but the spacing of the pill still stuck there

Screenshot Attached

![Screenshot_20231015-151541_Brave](https://github.com/Coxxs/hide-tablet-taskbar/assets/100989709/5aa3ac92-f317-4648-b211-557f21e8e0dc)

**Comment by Coxxs** [comment]
This repo is not related to AOSPMods
